os: linux
dist: bionic
language: python
cache:
  pip: true
  directories:
    - $HOME/stanza_resources
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -e .[all]

script:
  - python setup.py test

# for codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
